version: "3.8"

services:
 
  doctor:
    hostname: 'doctor'
    build:
      context: ./doctor
      dockerfile: Dockerfile
    image: borenlew/doctor:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_doctor
      PYTHONUNBUFFERED: 1
    ports: 
    - "5200:5200"
    # hostname: 'doctor'
 
  appt:
    hostname: 'appt'
    build:
      context: ./appt
      dockerfile: Dockerfile
    image: borenlew/appt:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_appt
      PYTHONUNBUFFERED: 1
    ports: 
    - "5100:5100"
    # hostname: 'appt'

  prescription:
    hostname: 'prescription'
    build:
      context: ./prescription
      dockerfile: Dockerfile
    image: borenlew/prescription:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_prescription
      PYTHONUNBUFFERED: 1
    ports: 
    - "5300:5300"
      
  patient:
    hostname: 'patient'
    build:
      context: ./patient
      dockerfile: Dockerfile
    image: borenlew/patient:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_patient
      PYTHONUNBUFFERED: 1
    ports: 
    - "5500:5500"

  bookingappt:
    hostname: 'bookingappt'
    build:
      context: ./bookingappt
      dockerfile: Dockerfile
    image: borenlew/bookingappt:g1t6_v2
    restart: always
    depends_on:
    - doctor
    - patient
    - prescription
    - appt
    environment:
      doctor_URL: http://doctor:5200/doctor
      appt_URL: http://appt:5100/appt/
      PYTHONUNBUFFERED: 1
    ports:
      - "5400:5400"
