version: "3.8"

volumes:
  rabbitmq_data:

services:
  ####################################
  # Simple Microservices  
  ####################################
  doctor:
    hostname: 'doctor'
    build:
      context: ./doctor
      dockerfile: Dockerfile
    image: borenlew/doctor:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_doctor
      PYTHONUNBUFFERED: 1
    ports: 
    - "5200:5200"
    # hostname: 'doctor'

  appt:
    hostname: 'appt'
    build:
      context: ./appt
      dockerfile: Dockerfile
    image: jthm/appt:g1t6_v3
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_appt
      PYTHONUNBUFFERED: 1
    ports: 
    - "5100:5100"
    # hostname: 'appt'

  prescription:
    hostname: 'prescription'
    build:
      context: ./prescription
      dockerfile: Dockerfile
    image: jthm/prescription:g1t6
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_prescription
      PYTHONUNBUFFERED: 1
    ports: 
    - "5300:5300"
      
  patient:
    hostname: 'patient'
    build:
      context: ./patient
      dockerfile: Dockerfile
    image: jthm/patient:g1t6
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_patient
      PYTHONUNBUFFERED: 1
    ports: 
    - "5500:5500"

  ####################################
  # Complex Microservices  
  ####################################
  bookingappt:
    hostname: 'bookingappt'
    build:
      context: ./bookingappt
      dockerfile: Dockerfile
    image: borenlew/bookingappt:g1t6_v2
    restart: always
    depends_on:
    - doctor
    - patient
    - prescription
    - appt
    environment:
      doctor_URL: http://doctor:5200/doctor
      appt_URL: http://appt:5100/appt/
      PYTHONUNBUFFERED: 1
    ports:
      - "5400:5400"

  consultationinfo:
    hostname: 'consultationinfo'
    build:
      context: ./consultationinfo
      dockerfile: Dockerfile
    image: jthm/consultationinfo:g1t6
    restart: always
    depends_on:
    - doctor
    - patient
    - prescription
    - appt
    environment:
      patient_URL: http://patient:5500/patient
      prescription_URL: http://prescription:5300/prescription
      doctAppt_URL: http://appt:5100/doctor/appt/
      PYTHONUNBUFFERED: 1
    ports:
      - "5600:5600"

  patientlogin:
    hostname: 'patientlogin'
    build:
      context: ./finish
      dockerfile: patientlogin.Dockerfile
    image: borenlew/patientlogin:g1t6_v2
    restart: always
    ports: 
    - "5800:5800"
    depends_on:
      - rabbitmq
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_patient
      PYTHONUNBUFFERED: 1
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  employeelogin:
    hostname: 'employeelogin'
    build:
      context: ./finish
      dockerfile: emplogin.Dockerfile
    image: borenlew/employeelogin:g1t6_v2
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/g1t6_employee
      PYTHONUNBUFFERED: 1
    ports: 
    - "5900:5900"



  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  login_log:
    build:
      context: ./login_log
      dockerfile: Dockerfile
    image: borenlew/login_log:g1t6_v2
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1